### PR TITLE
Fix pip index URL.

### PR DESCRIPTION
**Pull request by xkszltl**
ROOT_DIR wasn't set so the URL was empty.
For CI there is no difference because the official one is already fast enough. But docker build would be slow if we run it elsewhere.

### CODE REVIEW

**Review by chenhao94 — COMMENTED** [review]
Since you have touched docker, should we also install gh in it?

**Comment by xkszltl** [comment]
Why?

**Comment by xkszltl** [comment]
Asking because it requires extra repo.
Also I'm not gonna refresh the docker after this PR because it has no runtime benefit.

**Comment by chenhao94** [comment]
> Why?

Then we may be able to do some GH-related issue in Docker container. (Creating releases, etc.)

Also, do you think we should upgrade to Bazel 6.1? It stops downloading the JDK stuff that we do not want. See [here](https://github.com/bazelbuild/bazel/issues/15088).

**Comment by xkszltl** [comment]
I'm OK with that

**Review by chenhao94 — APPROVED** [review]

**Pull request merged**
