### PR TITLE
Add cinttypes to cr signal

### PR DESCRIPTION
**Pull request by zhouxindong**
reorder header cinttypes to the right position

### CODE REVIEW

**Comment by zhouxindong** [comment]
forget something, close it, and rePR

**Comment by zhouxindong** [comment]
I forget add reviewers from team, sorry

**Comment by xkszltl** [comment]
Please describe the issue you're fixing (maybe with the compile error log you sent me in chat) in the first msg (you can edit it) or in the git commit msg if it's a single-commit PR, so that it can be well tracked in history.

**Comment by zhouxindong** [comment]
@xkszltl I got it, I will fix the git commit history, amend with the compile error!

**Comment by xkszltl** [comment]
You don't need to close a PR.
If you want to amend the history, simply force-push it with the same branch.

**Pull request closed without merging**
